CREATE TABLE PageViews
(
        day DATE,
        home INT(15) NOT NULL,
        people INT(15) NOT NULL,
        map INT(15) NOT NULL,
        shuttleschedule INT(15) NOT NULL,
        calendar INT(15) NOT NULL,
        stellar INT(15) NOT NULL,
        careers INT(15) NOT NULL,
        emergency INT(15) NOT NULL,
        3down INT(15) NOT NULL,
        links INT(15) NOT NULL,
        mobile_about INT(15) NOT NULL,
        ip INT(15) NOT NULL,
        sp INT(15) NOT NULL,
        fp INT(15) NOT NULL,
        computer INT(15) NOT NULL,
        PRIMARY KEY(day)
)
;
